# Generated by Django 4.2.7 on 2024-01-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0006_alter_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Head',
            field=models.CharField(default='', max_length=200),
        ),
    ]
