# Generated by Django 4.2.7 on 2024-01-26 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0007_employee_head'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='admins',
            new_name='hr',
        ),
        migrations.AlterModelTable(
            name='hr',
            table='hr',
        ),
    ]
