# Generated by Django 4.2.7 on 2024-01-28 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0010_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.IntegerField()),
                ('absent', models.IntegerField()),
                ('totalworkingdays', models.IntegerField()),
                ('paymenttobepaid', models.FloatField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectapp.employee')),
            ],
            options={
                'db_table': 'account',
            },
        ),
    ]
