# Generated by Django 4.2.7 on 2024-01-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0011_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Salary',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='head',
            name='Salary',
            field=models.FloatField(default=0),
        ),
    ]
