# Generated by Django 4.2.7 on 2024-02-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0012_employee_salary_head_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Designation', models.CharField(max_length=200)),
                ('Department', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'accountant',
            },
        ),
    ]
