# Generated by Django 4.2.7 on 2024-02-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0014_leaverequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
