# Generated by Django 4.2.7 on 2024-02-04 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0016_leaverequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
    ]
