# Generated by Django 4.2.7 on 2024-02-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0019_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='month',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
