# Generated by Django 4.2.7 on 2024-02-07 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0022_delete_event_payment_paymenttobepaid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='paymenttobepaid',
            new_name='salaryamount',
        ),
    ]
